### ISSUE TITLE
Missing Video recorder after submission

### ISSUE THREAD

**Issue by azanoni** [Ziggeo/ziggeo-wp-video-for-fluent-forms#3]
Hi, we updated to the latest version and we found a bug in the data that fluentsform store after the video is submitted

![image](https://github.com/Ziggeo/ziggeo-wp-video-for-fluent-forms/assets/21685626/02660bbf-8416-4e71-ad2b-e452308726c3)

In the previous screenshot you could see that the previous entrie from 11 Sept stored this:

[ziggeoplayer]a47f612995447d703c6af356cc51baa7[/ziggeoplayer]

But the new one, is not recorded anything, we also check the admin settings but sadly we cannot change to another option because always is being saved with the first one (WP Embed code)

![image](https://github.com/Ziggeo/ziggeo-wp-video-for-fluent-forms/assets/21685626/a82cf027-5e81-445b-9b9a-601f1b2f19e1)

Thanks in advance

**Comment by Bane-D** [comment]
Hi Alfredo, looking into this for you.

**Comment by Bane-D** [comment]
Hi Alfredo, sorry to keep you waiting on this.

There were couple of issues with the code causing this. One of which was a typo. I have made the changes and they are now available in the latest update 1.7

Please let me know how it goes once you had a chance to test it out.
